fix: codespace node version is outdated
Due to the usage of new functionality introduced in node 16 there are
unresolvable complications with the default node version of codespaces.

Error: splitHandle.at is not a function

Ref: https://github.com/microsoft/vscode-remote-try-node